# Generated by Django 5.2.4 on 2025-08-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('waste_recycling', 'Waste & Recycling'), ('upcycling_diy', 'Upcycling & DIY'), ('sustainable_living', 'Sustainable Living Tips'), ('food_composting', 'Food & Composting'), ('green_tech', 'Green Tech & Innovation'), ('community_events', 'Community & Events')], db_index=True, default='waste_recycling', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
